before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "unjxde/godash:latest"
      - "unjxde/godash:v{{ .Major }}"
      - "unjxde/godash:{{ .Tag }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - entrypoint.sh
      - bookmarks/config.yaml
      - tailwind.config.js
      - package.json
      - package-lock.json
      - static
      - templates
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "unjxde/godash:latest"
      - "unjxde/godash:v{{ .Major }}"
      - "unjxde/godash:{{ .Tag }}"
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
    extra_files:
      - entrypoint.sh
      - bookmarks/config.yaml
      - tailwind.config.js
      - package.json
      - package-lock.json
      - static
      - templates
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
source:
  enabled: true
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
