before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
dockers:
  - use: buildx
    goos: linux
    goarch: amd64
    image_templates:
      - "unjxde/{{ .ProjectName }}:latest-amd64"
      - "unjxde/{{ .ProjectName }}:v{{ .Major }}-amd64"
      - "unjxde/{{ .ProjectName }}:{{ .Tag }}-amd64"
    build_flag_templates:
      - "--platform=linux/amd64"
    extra_files:
      - entrypoint.sh
      - bookmarks/config.yaml
      - tailwind.config.js
      - package.json
      - package-lock.json
      - static
      - templates
  - use: buildx
    goos: linux
    goarch: arm64
    image_templates:
      - "unjxde/{{ .ProjectName }}:latest-arm64v8"
      - "unjxde/{{ .ProjectName }}:v{{ .Major }}-arm64v8"
      - "unjxde/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
    build_flag_templates:
      - "--platform=linux/arm64/v8"
    extra_files:
      - entrypoint.sh
      - bookmarks/config.yaml
      - tailwind.config.js
      - package.json
      - package-lock.json
      - static
      - templates
docker_manifests:
  - name_template: "unjxde/{{ .ProjectName }}:v{{ .Tag }}"
    image_templates:
      - "unjxde/{{ .ProjectName }}:{{ .Tag }}-amd64"
      - "unjxde/{{ .ProjectName }}:{{ .Tag }}-arm64v8"
  - name_template: "unjxde/{{ .ProjectName }}:v{{ .Major }}"
    image_templates:
      - "unjxde/{{ .ProjectName }}:{{ .Major }}-amd64"
      - "unjxde/{{ .ProjectName }}:{{ .Major }}-arm64v8"
  - name_template: "unjxde/{{ .ProjectName }}:latest"
    image_templates:
      - "unjxde/{{ .ProjectName }}:latest-amd64"
      - "unjxde/{{ .ProjectName }}:latest-arm64v8"
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
