FROM golang:1.20-alpine
RUN apk add --update --no-cache tzdata

RUN go install github.com/cosmtrek/air@latest

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

ENV VERSION=v0.0.0-DEV
ENV DATE=2023-04-05T20:48:07Z

CMD ["air", "-c", ".air.toml"]
