links:
  - category: "Services & Tools"
    entries:
      - name: "Blog"
        url: "https://www.cestlavie.moe/"
      - name: "Status"
        url: "https://uptime.cestlavie.moe/status/monitor"
      - name: "Typing Exercises"
        url: "https://typing.cestlavie.moe/"
      - name: "Umami"
        url: "https://umami.cestlavie.moe/"
      - name: "AriaNg"
        url: "https://ariang.cestlavie.moe/"
      - name: "Coverview"
        url: "https://cover.cestlavie.moe/"
      - name: "Yacd"
        url: "https://yacd.cestlavie.moe/"
      - name: "CTFever"
        url: "https://ctf.cestlavie.moe"
